/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service health
     * @description Checks database, cache and broker connectivity.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get my profile
     * @description Any logged-in user (users.profile.read_own). Returns ETag.
     */
    get: operations["get_me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Purpose of this API is to edit my first and last name
     * @description Any logged-in user (users.profile.update_own). Only first_name and last_name can change; email, role and status cannot. If-Match is optional.
     */
    patch: operations["update_me_v1_me_patch"];
    trace?: never;
  };
  "/v1/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list roles
     * @description Admin only (users.user.invite). The two roles for the Invite User form. Not paginated.
     */
    get: operations["list_roles_v1_roles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list users
     * @description Admin only (users.user.read_all). Search by name or email; filter by status and role; sort by first_name, email or created_at. 20 per page by default.
     */
    get: operations["list_users_v1_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get one user
     * @description Admin only (users.user.read_all). Returns ETag; send If-None-Match to get 304 when unchanged.
     */
    get: operations["get_user_v1_users__user_id__get"];
    put?: never;
    post?: never;
    /**
     * Purpose of this API is to delete a user permanently
     * @description Admin only (users.user.delete). Requires If-Match. Hard delete: the user and all their assignments, Todos, history and tokens are removed and disappear from past reports. An Admin cannot delete their own account. Call GET /v1/users/{user_id}/delete-preview first to show the impact.
     */
    delete: operations["delete_user_v1_users__user_id__delete"];
    options?: never;
    head?: never;
    /**
     * Purpose of this API is to activate or deactivate a user
     * @description Admin only (users.user.update_status). Requires If-Match. INACTIVE logs the user out on their next request and stops new Todos; ACTIVE (from INACTIVE) resumes Todos from today. An Admin cannot change their own status; an INVITED user becomes ACTIVE only by accepting the invitation.
     */
    patch: operations["change_user_status_v1_users__user_id__patch"];
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to log in
     * @description Public. Email + password. Returns an access token (1 hour) and a refresh token (7 days). Wrong email, wrong password and not-yet-accepted invitations all give 401 INVALID_CREDENTIALS. An inactive account gives 403 ACCOUNT_INACTIVE. Rate limited.
     */
    post: operations["login_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is OAuth2 login for Swagger
     * @description Public. Form fields `username` (email) and `password`. Used by Swagger's Authorize button. Returns the OAuth2 format {access_token, token_type} (documented exception to the response envelope).
     */
    post: operations["token_v1_auth_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to renew tokens
     * @description Public (refresh token in the body). Rotation: the old refresh token stops working and a new pair is returned. Reusing an old refresh token logs the user out everywhere (401 TOKEN_REUSED).
     */
    post: operations["refresh_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to log out this device
     * @description Logged-in user. Revokes the given refresh token. Idempotent.
     */
    post: operations["logout_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get my permissions
     * @description Any logged-in user (users.profile.read_own). The role and permission codes, used by the frontend to show or hide menu items and buttons.
     */
    get: operations["my_permissions_v1_me_permissions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Purpose of this API is to change my password
     * @description Any logged-in user (users.profile.update_own). Requires the current password. This device (given refresh_token) stays logged in; all others are logged out.
     */
    patch: operations["change_password_v1_me_password_patch"];
    trace?: never;
  };
  "/v1/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to invite a user
     * @description Admin only (users.user.invite). Creates the user as INVITED and emails a link valid for 24 hours (sent in the background). Email must be unique (409 DUPLICATE_EMAIL).
     */
    post: operations["invite_v1_invitations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/invitations/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to check an invitation link
     * @description Public. Returns the invitee's name and email, or 422 LINK_INVALID_OR_EXPIRED.
     */
    post: operations["verify_invitation_v1_invitations_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/invitations/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to accept an invitation
     * @description Public. Sets the password (8-16 characters, a letter and a digit) and activates the account. The link works once.
     */
    post: operations["accept_invitation_v1_invitations_accept_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{user_id}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to re-send an invitation
     * @description Admin only (users.user.invite). The previous link stops working; a new one (24 hours) is emailed. Only for INVITED users.
     */
    post: operations["resend_invitation_v1_users__user_id__invitations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to request a password reset link
     * @description Public. Always returns 202 with the same message, whether or not the email exists. The link is valid for 1 hour. Rate limited.
     */
    post: operations["forgot_password_v1_auth_forgot_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{user_id}/password-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to send a change-password link
     * @description Admin only (users.user.send_password_link). For ACTIVE users. Link valid for 1 hour.
     */
    post: operations["send_password_link_v1_users__user_id__password_links_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/reset-password/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to check a password reset link
     * @description Public. Returns the email, or 422 LINK_INVALID_OR_EXPIRED.
     */
    post: operations["verify_reset_v1_auth_reset_password_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to set a new password from a link
     * @description Public. Works once. Logs the user out on every device.
     */
    post: operations["reset_password_v1_auth_reset_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/task-types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list task types and their answers
     * @description Any logged-in user (assignments.todo.read_own). The four types (Time, Yes-No, Food, Number) with the answers users can give. Number also accepts Other (a whole number of 5 or more).
     */
    get: operations["list_task_types_v1_task_types_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list tasks
     * @description Admin only (activities.task.read_all). Search by name; filter by type and status; sort by name or updated_at. 20 per page by default.
     */
    get: operations["list_tasks_v1_tasks_get"];
    put?: never;
    /**
     * Purpose of this API is to create a task
     * @description Admin only (activities.task.create). New tasks are ACTIVE. Name is unique (ignoring case, 409 DUPLICATE_TASK_NAME). The type can't be changed later.
     */
    post: operations["create_task_v1_tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get one task
     * @description Admin only (activities.task.read_all). Returns ETag; send If-None-Match to get 304.
     */
    get: operations["get_task_v1_tasks__task_id__get"];
    put?: never;
    post?: never;
    /**
     * Purpose of this API is to delete a task permanently
     * @description Admin only (activities.task.delete). Requires If-Match. Hard delete: the task, all its assignments and all its Todos for every user are removed, and past reports change. Call GET /v1/tasks/{task_id}/delete-preview first to show the impact.
     */
    delete: operations["delete_task_v1_tasks__task_id__delete"];
    options?: never;
    head?: never;
    /**
     * Purpose of this API is to edit, activate or deactivate a task
     * @description Admin only (activities.task.update). Requires If-Match. Name and description can change (renaming applies to past history too); the type can't (422 FIELD_NOT_EDITABLE). INACTIVE stops new Todos from tomorrow; pending Todos stay answerable. ACTIVE (from INACTIVE) creates today's Todos where due, in the background; missed days are not filled in.
     */
    patch: operations["update_task_v1_tasks__task_id__patch"];
    trace?: never;
  };
  "/v1/assignments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list assignments
     * @description Admin only (assignments.assignment.read_all). Filter by user, task, frequency and status (ACTIVE by default, ENDED, ALL); sort by user_name, task_name, start_date or created_at.
     */
    get: operations["list_assignments_v1_assignments_get"];
    put?: never;
    /**
     * Purpose of this API is to assign a task to users
     * @description Admin only (assignments.assignment.create). Send `user_ids` or `all_users=true` (every ACTIVE user now). Users who already have the task are skipped and listed. Start date defaults to today and must be today or later; weekdays are required for WEEKLY. If due today, today's Todo is created now.
     */
    post: operations["assign_task_v1_assignments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assignments/copy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purpose of this API is to copy a user's assignments to other users
     * @description Admin only (assignments.assignment.copy). Copies the source's active assignments (active tasks, not past their end date) with the same frequency, weekdays, start and end dates. Tasks a target already has are skipped. `dry_run=true` returns the preview without changing anything.
     */
    post: operations["copy_assignments_v1_assignments_copy_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assignments/due-dates-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to preview the next due dates of a schedule
     * @description Admin only (assignments.assignment.create). Helper for the Assign / Change Frequency forms. `weekdays` is comma-separated, e.g. MON,THU.
     */
    get: operations["due_dates_preview_v1_assignments_due_dates_preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assignments/{assignment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get one assignment
     * @description Admin only (assignments.assignment.read_all). Includes the next 3 due dates. Returns ETag.
     */
    get: operations["get_assignment_v1_assignments__assignment_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Purpose of this API is to change frequency, change end date, or de-assign
     * @description Admin only (assignments.assignment.update). Requires If-Match. One change per request: (1) `frequency` (+ `weekdays`, optional `start_date`): pending Todos from today on are replaced; completed and past pending Todos stay. (2) `end_date` (null removes it): set, extend or shorten; extending an assignment that ended by its end date makes it active again. (3) `status: ENDED`: de-assign; today's and past pending Todos stay answerable. A de-assigned assignment can't be changed (assign again instead).
     */
    patch: operations["update_assignment_v1_assignments__assignment_id__patch"];
    trace?: never;
  };
  "/v1/me/todos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list my pending Todos for a date
     * @description Any logged-in user (assignments.todo.read_own). Pending Todos only (answered ones are in history), for `date` (default today, IST; past dates allowed). Filter by frequency, search by task name.
     */
    get: operations["my_todos_v1_me_todos_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/todos/calendar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get my pending-dates calendar
     * @description Any logged-in user (assignments.todo.read_own). Dates of `month` (YYYY-MM, default current) that have pending Todos, with counts. Includes the server's `today`.
     */
    get: operations["my_calendar_v1_me_todos_calendar_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/todos/pending-counts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get my pending counts per year and per month
     * @description Any logged-in user (assignments.todo.read_own). Every year from my first Todo to this year, and the 12 months of `year` (default this year), each with its pending Todos (zeros included).
     */
    get: operations["my_pending_counts_v1_me_todos_pending_counts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/todos/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get my dashboard counts
     * @description Any logged-in user (assignments.todo.read_own). Pending Todos due on `date` (default today), per frequency (all seven). Includes the server's `today`.
     */
    get: operations["my_summary_v1_me_todos_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/todos/{todo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Purpose of this API is to answer a Todo
     * @description Any logged-in user, own Todos only (assignments.todo.respond_own). The answer must suit the task type (Time HH:MM; Yes/No; Food; Number 1-4 or No, or `is_other` with a whole number of 5 or more). Any answer, including No, completes the Todo. Answers can't be changed (409). If-Match optional.
     */
    patch: operations["answer_todo_v1_me_todos__todo_id__patch"];
    trace?: never;
  };
  "/v1/me/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list my completed Todos
     * @description Any logged-in user (assignments.history.read_own). Default range: the current week (Mon-Sun); at most one year. Filter by task and frequency. Newest due date first.
     */
    get: operations["my_history_v1_me_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list the tasks I have or had an assignment for
     * @description Any logged-in user (assignments.history.read_own). Current names, A-Z, any assignment status; used by the Task filter of My History.
     */
    get: operations["my_tasks_v1_me_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to list completed Todos of all users
     * @description Admin only (assignments.history.read_all). Same as my history, plus a `user_id` filter; each item includes the user.
     */
    get: operations["all_history_v1_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{user_id}/delete-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to preview what deleting a user removes
     * @description Admin only (users.user.delete). Counts of assignments, Todos and completed Todos. Deletes nothing. All zero for an invited user.
     */
    get: operations["user_delete_preview_v1_users__user_id__delete_preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tasks/{task_id}/delete-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to preview what deleting a task removes
     * @description Admin only (activities.task.delete). Users affected, assignments, Todos and completed Todos. Deletes nothing.
     */
    get: operations["task_delete_preview_v1_tasks__task_id__delete_preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get the report for all users or one user
     * @description Admin only (reporting.report.read_all). Range: `range_type` DAY (default, today; or `day`), WEEK (Mon-Sun; `week_start` must be a Monday), MONTH (`month` YYYY-MM), CUSTOM (`date_from` + `date_to`, at most one year). Per frequency (all seven): total, completed (includes No), no, pending, status (NO_TASK if total is 0, PENDING if anything is pending, otherwise COMPLETE). A Todo counts on its due date. `summary` covers all selected users; `users` is paginated (20 per page, by name) and includes inactive users (marked) and users with no Todos (all NO_TASK). No export.
     */
    get: operations["get_report_v1_reports_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Purpose of this API is to get my report
     * @description Any logged-in user (reporting.report.read_own). Range: `range_type` DAY (default, today; or `day`), WEEK (Mon-Sun; `week_start` must be a Monday), MONTH (`month` YYYY-MM), CUSTOM (`date_from` + `date_to`, at most one year). Per frequency (all seven): total, completed (includes No), no, pending, status (NO_TASK if total is 0, PENDING if anything is pending, otherwise COMPLETE). A Todo counts on its due date.
     */
    get: operations["get_my_report_v1_me_report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AcceptInvitationRead */
    AcceptInvitationRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Status */
      status: string;
    };
    /** AcceptInvitationRequest */
    AcceptInvitationRequest: {
      /** Token */
      token: string;
      /** Password */
      password: string;
    };
    /** AssignCreatedItem */
    AssignCreatedItem: {
      /**
       * Assignment Id
       * Format: uuid
       */
      assignment_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Next Due Dates */
      next_due_dates: string[];
    };
    /** AssignResultRead */
    AssignResultRead: {
      /** Created */
      created: components["schemas"]["AssignCreatedItem"][];
      /** Skipped */
      skipped: components["schemas"]["AssignSkippedItem"][];
    };
    /** AssignSkippedItem */
    AssignSkippedItem: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Reason */
      reason: string;
    };
    /**
     * AssignmentCreate
     * @description POST /v1/assignments — one task to one, several or all ACTIVE users (ASG-R1–R6).
     */
    AssignmentCreate: {
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /** User Ids */
      user_ids?: string[] | null;
      /**
       * All Users
       * @default false
       */
      all_users: boolean;
      /**
       * Frequency
       * @enum {string}
       */
      frequency:
        "DAILY" | "WEEKLY" | "EVERY_15_DAYS" | "MONTHLY" | "QUARTERLY" | "SIX_MONTHS" | "YEARLY";
      /**
       * Weekdays
       * @default []
       */
      weekdays: ("MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN")[];
      /**
       * Start Date
       * @description Default today (IST); today or later
       */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** AssignmentRead */
    AssignmentRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      user: components["schemas"]["AssignmentUserRead"];
      task: components["schemas"]["AssignmentTaskRead"];
      /** Frequency */
      frequency: string;
      /** Weekdays */
      weekdays: string[];
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** End Date */
      end_date: string | null;
      /** Status */
      status: string;
      /** Ended Reason */
      ended_reason: string | null;
      /** Ended On */
      ended_on: string | null;
      /** Is Copied */
      is_copied: boolean;
      /** Next Due Dates */
      next_due_dates: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Created By */
      created_by: string | null;
      /** Updated By */
      updated_by: string | null;
    };
    /** AssignmentTaskRead */
    AssignmentTaskRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Type */
      type: string;
      /** Status */
      status: string;
    };
    /**
     * AssignmentUpdate
     * @description PATCH /v1/assignments/{assignment_id} — exactly one change type per request:
     *
     *     - change frequency: `frequency` (+ `weekdays`), optional `start_date` (default today)
     *     - change end date: `end_date` (null removes it)
     *     - de-assign: `status` = "ENDED"
     */
    AssignmentUpdate: {
      /** Frequency */
      frequency?:
        | ("DAILY" | "WEEKLY" | "EVERY_15_DAYS" | "MONTHLY" | "QUARTERLY" | "SIX_MONTHS" | "YEARLY")
        | null;
      /** Weekdays */
      weekdays?: ("MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN")[] | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Status */
      status?: "ENDED" | null;
    };
    /** AssignmentUserRead */
    AssignmentUserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Email */
      email: string;
      /** Status */
      status: string;
    };
    /** Body_token_v1_auth_token_post */
    Body_token_v1_auth_token_post: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** CalendarDay */
    CalendarDay: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Pending Count */
      pending_count: number;
    };
    /** CalendarRead */
    CalendarRead: {
      /** Month */
      month: string;
      /**
       * Today
       * Format: date
       */
      today: string;
      /** Days */
      days: components["schemas"]["CalendarDay"][];
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
      /**
       * Refresh Token
       * @description This device's token; kept alive
       */
      refresh_token: string;
    };
    /** CopyRequest */
    CopyRequest: {
      /**
       * Source User Id
       * Format: uuid
       */
      source_user_id: string;
      /** Target User Ids */
      target_user_ids: string[];
      /**
       * Dry Run
       * @default false
       */
      dry_run: boolean;
    };
    /** CopyResultRead */
    CopyResultRead: {
      /** Dry Run */
      dry_run: boolean;
      /** Targets */
      targets: components["schemas"]["CopyTargetResult"][];
    };
    /** CopySkippedItem */
    CopySkippedItem: {
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /** Task Name */
      task_name: string;
      /** Reason */
      reason: string;
    };
    /** CopyTargetResult */
    CopyTargetResult: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Copied */
      copied: components["schemas"]["CopyTaskItem"][];
      /** Skipped */
      skipped: components["schemas"]["CopySkippedItem"][];
    };
    /** CopyTaskItem */
    CopyTaskItem: {
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /** Task Name */
      task_name: string;
      /** Frequency */
      frequency: string;
      /** Weekdays */
      weekdays: string[];
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** End Date */
      end_date: string | null;
      /** Assignment Id */
      assignment_id?: string | null;
    };
    /** DueDatesRead */
    DueDatesRead: {
      /** Due Dates */
      due_dates: string[];
    };
    /** ErrorDetail */
    ErrorDetail: {
      /** Field */
      field: string;
      /** Issue */
      issue: string;
    };
    /**
     * ErrorInfo
     * @description Only `code` and `details`; `message` lives at the root.
     */
    ErrorInfo: {
      /** Code */
      code: string;
      /**
       * Details
       * @default []
       */
      details: components["schemas"]["ErrorDetail"][];
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /**
     * FrequencyCounts
     * @description T, C, N, P, S for one frequency. Always total = completed + pending; `no` is part of `completed`.
     */
    FrequencyCounts: {
      /** Frequency */
      frequency: string;
      /** Total */
      total: number;
      /** Completed */
      completed: number;
      /** No */
      no: number;
      /** Pending */
      pending: number;
      /** Status */
      status: string;
    };
    /** FrequencyPending */
    FrequencyPending: {
      /** Frequency */
      frequency: string;
      /** Pending */
      pending: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HistoryItemRead */
    HistoryItemRead: {
      /**
       * Todo Id
       * Format: uuid
       */
      todo_id: string;
      /**
       * Due Date
       * Format: date
       */
      due_date: string;
      task: components["schemas"]["HistoryTaskRead"];
      /** Frequency */
      frequency: string;
      /** Response Value */
      response_value: string;
      /** Is Other */
      is_other: boolean;
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string;
      user?: components["schemas"]["HistoryUserRead"] | null;
    };
    /** HistoryTaskRead */
    HistoryTaskRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Type */
      type: string;
    };
    /** HistoryUserRead */
    HistoryUserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Status */
      status: string;
    };
    /** InvitationInfoRead */
    InvitationInfoRead: {
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Email */
      email: string;
    };
    /** InviteRequest */
    InviteRequest: {
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Role Id
       * Format: uuid
       */
      role_id: string;
    };
    /** InviteResultRead */
    InviteResultRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      role: components["schemas"]["RoleRead"];
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Created By */
      created_by: string | null;
      /** Updated By */
      updated_by: string | null;
      /**
       * Invitation Expires At
       * Format: date-time
       */
      invitation_expires_at: string;
    };
    /**
     * LinkTokenRequest
     * @description Verify an invitation or reset link. The token travels in the body, never in the URL.
     */
    LinkTokenRequest: {
      /** Token */
      token: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginUserRead */
    LoginUserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      role: components["schemas"]["RoleRead"];
    };
    /** LogoutRequest */
    LogoutRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** MonthPending */
    MonthPending: {
      /** Month */
      month: string;
      /** Pending */
      pending: number;
    };
    /**
     * MyPermissionsRead
     * @description GET /v1/me/permissions.
     */
    MyPermissionsRead: {
      role: components["schemas"]["RoleRead"];
      /** Permissions */
      permissions: string[];
    };
    /**
     * MyReportRead
     * @description GET /v1/me/report — the caller's own counts.
     */
    MyReportRead: {
      range: components["schemas"]["ReportRange"];
      user: components["schemas"]["ReportUserRead"];
      /** Summary */
      summary: components["schemas"]["FrequencyCounts"][];
    };
    /**
     * MyTaskListRead
     * @description GET /v1/me/tasks: the tasks the caller has or had an assignment for (filters on My History).
     */
    MyTaskListRead: {
      /** Items */
      items: components["schemas"]["HistoryTaskRead"][];
    };
    /**
     * OAuth2TokenRead
     * @description POST /v1/auth/token — OAuth2 format for Swagger (documented exception to the envelope).
     */
    OAuth2TokenRead: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** PaginatedResponse[AssignmentRead] */
    PaginatedResponse_AssignmentRead_: {
      /** Items */
      items: components["schemas"]["AssignmentRead"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Next Page */
      next_page?: string | null;
      /** Prev Page */
      prev_page?: string | null;
    };
    /** PaginatedResponse[HistoryItemRead] */
    PaginatedResponse_HistoryItemRead_: {
      /** Items */
      items: components["schemas"]["HistoryItemRead"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Next Page */
      next_page?: string | null;
      /** Prev Page */
      prev_page?: string | null;
    };
    /** PaginatedResponse[ReportUserRow] */
    PaginatedResponse_ReportUserRow_: {
      /** Items */
      items: components["schemas"]["ReportUserRow"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Next Page */
      next_page?: string | null;
      /** Prev Page */
      prev_page?: string | null;
    };
    /** PaginatedResponse[TaskRead] */
    PaginatedResponse_TaskRead_: {
      /** Items */
      items: components["schemas"]["TaskRead"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Next Page */
      next_page?: string | null;
      /** Prev Page */
      prev_page?: string | null;
    };
    /** PaginatedResponse[TodoRead] */
    PaginatedResponse_TodoRead_: {
      /** Items */
      items: components["schemas"]["TodoRead"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Next Page */
      next_page?: string | null;
      /** Prev Page */
      prev_page?: string | null;
    };
    /** PaginatedResponse[UserRead] */
    PaginatedResponse_UserRead_: {
      /** Items */
      items: components["schemas"]["UserRead"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Next Page */
      next_page?: string | null;
      /** Prev Page */
      prev_page?: string | null;
    };
    /** PasswordLinkRead */
    PasswordLinkRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /**
     * PendingCountsRead
     * @description Year and month views of the pending-dates calendar: pending Todos per year and per month.
     */
    PendingCountsRead: {
      /** Year */
      year: number;
      /**
       * Today
       * Format: date
       */
      today: string;
      /** Years */
      years: components["schemas"]["YearPending"][];
      /** Months */
      months: components["schemas"]["MonthPending"][];
    };
    /**
     * ProfileUpdate
     * @description PATCH /v1/me — first and last name only (USR-R2).
     */
    ProfileUpdate: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** ReportRange */
    ReportRange: {
      /** Range Type */
      range_type: string;
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /**
       * Today
       * Format: date
       */
      today: string;
    };
    /**
     * ReportRead
     * @description GET /v1/reports — summary over ALL selected users, plus a paginated list of user rows
     *     (documented variation of Rule 5: the pagination fields sit inside `users`).
     */
    ReportRead: {
      range: components["schemas"]["ReportRange"];
      /** Summary */
      summary: components["schemas"]["FrequencyCounts"][];
      users: components["schemas"]["PaginatedResponse_ReportUserRow_"];
    };
    /** ReportUserRead */
    ReportUserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /** Email */
      email: string;
      /** Status */
      status: string;
    };
    /** ReportUserRow */
    ReportUserRow: {
      user: components["schemas"]["ReportUserRead"];
      /** Frequencies */
      frequencies: components["schemas"]["FrequencyCounts"][];
    };
    /** ResendInvitationRead */
    ResendInvitationRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Invitation Expires At
       * Format: date-time
       */
      invitation_expires_at: string;
    };
    /** ResetInfoRead */
    ResetInfoRead: {
      /** Email */
      email: string;
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /**
     * RoleListRead
     * @description GET /v1/roles — fixed list of two, not paginated.
     */
    RoleListRead: {
      /** Items */
      items: components["schemas"]["RoleRead"][];
    };
    /** RoleRead */
    RoleRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /** Name */
      name: string;
    };
    /** StandardResponse[AcceptInvitationRead] */
    StandardResponse_AcceptInvitationRead_: {
      data?: components["schemas"]["AcceptInvitationRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[AssignResultRead] */
    StandardResponse_AssignResultRead_: {
      data?: components["schemas"]["AssignResultRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[AssignmentRead] */
    StandardResponse_AssignmentRead_: {
      data?: components["schemas"]["AssignmentRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[CalendarRead] */
    StandardResponse_CalendarRead_: {
      data?: components["schemas"]["CalendarRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[CopyResultRead] */
    StandardResponse_CopyResultRead_: {
      data?: components["schemas"]["CopyResultRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[DueDatesRead] */
    StandardResponse_DueDatesRead_: {
      data?: components["schemas"]["DueDatesRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[InvitationInfoRead] */
    StandardResponse_InvitationInfoRead_: {
      data?: components["schemas"]["InvitationInfoRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[InviteResultRead] */
    StandardResponse_InviteResultRead_: {
      data?: components["schemas"]["InviteResultRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[MyPermissionsRead] */
    StandardResponse_MyPermissionsRead_: {
      data?: components["schemas"]["MyPermissionsRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[MyReportRead] */
    StandardResponse_MyReportRead_: {
      data?: components["schemas"]["MyReportRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[MyTaskListRead] */
    StandardResponse_MyTaskListRead_: {
      data?: components["schemas"]["MyTaskListRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[NoneType] */
    StandardResponse_NoneType_: {
      /** Data */
      data?: null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PaginatedResponse[AssignmentRead]] */
    StandardResponse_PaginatedResponse_AssignmentRead__: {
      data?: components["schemas"]["PaginatedResponse_AssignmentRead_"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PaginatedResponse[HistoryItemRead]] */
    StandardResponse_PaginatedResponse_HistoryItemRead__: {
      data?: components["schemas"]["PaginatedResponse_HistoryItemRead_"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PaginatedResponse[TaskRead]] */
    StandardResponse_PaginatedResponse_TaskRead__: {
      data?: components["schemas"]["PaginatedResponse_TaskRead_"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PaginatedResponse[TodoRead]] */
    StandardResponse_PaginatedResponse_TodoRead__: {
      data?: components["schemas"]["PaginatedResponse_TodoRead_"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PaginatedResponse[UserRead]] */
    StandardResponse_PaginatedResponse_UserRead__: {
      data?: components["schemas"]["PaginatedResponse_UserRead_"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PasswordLinkRead] */
    StandardResponse_PasswordLinkRead_: {
      data?: components["schemas"]["PasswordLinkRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[PendingCountsRead] */
    StandardResponse_PendingCountsRead_: {
      data?: components["schemas"]["PendingCountsRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[ReportRead] */
    StandardResponse_ReportRead_: {
      data?: components["schemas"]["ReportRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[ResendInvitationRead] */
    StandardResponse_ResendInvitationRead_: {
      data?: components["schemas"]["ResendInvitationRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[ResetInfoRead] */
    StandardResponse_ResetInfoRead_: {
      data?: components["schemas"]["ResetInfoRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[RoleListRead] */
    StandardResponse_RoleListRead_: {
      data?: components["schemas"]["RoleListRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[SummaryRead] */
    StandardResponse_SummaryRead_: {
      data?: components["schemas"]["SummaryRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[TaskDeletePreviewRead] */
    StandardResponse_TaskDeletePreviewRead_: {
      data?: components["schemas"]["TaskDeletePreviewRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[TaskRead] */
    StandardResponse_TaskRead_: {
      data?: components["schemas"]["TaskRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[TaskTypeListRead] */
    StandardResponse_TaskTypeListRead_: {
      data?: components["schemas"]["TaskTypeListRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[TodoRead] */
    StandardResponse_TodoRead_: {
      data?: components["schemas"]["TodoRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[TokenPairRead] */
    StandardResponse_TokenPairRead_: {
      data?: components["schemas"]["TokenPairRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[UserDeletePreviewRead] */
    StandardResponse_UserDeletePreviewRead_: {
      data?: components["schemas"]["UserDeletePreviewRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** StandardResponse[UserRead] */
    StandardResponse_UserRead_: {
      data?: components["schemas"]["UserRead"] | null;
      /** Message */
      message: string;
      error?: components["schemas"]["ErrorInfo"] | null;
    };
    /** SummaryRead */
    SummaryRead: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /**
       * Today
       * Format: date
       */
      today: string;
      /** Pending By Frequency */
      pending_by_frequency: components["schemas"]["FrequencyPending"][];
    };
    /** TaskCreate */
    TaskCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Type
       * @enum {string}
       */
      type: "TIME" | "YES_NO" | "FOOD" | "NUMBER";
    };
    /** TaskDeletePreviewRead */
    TaskDeletePreviewRead: {
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /** Users Affected */
      users_affected: number;
      /** Assignments */
      assignments: number;
      /** Todos Total */
      todos_total: number;
      /** Todos Completed */
      todos_completed: number;
    };
    /** TaskRead */
    TaskRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Type */
      type: string;
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Created By */
      created_by: string | null;
      /** Updated By */
      updated_by: string | null;
    };
    /** TaskTypeListRead */
    TaskTypeListRead: {
      /** Items */
      items: components["schemas"]["TaskTypeRead"][];
    };
    /** TaskTypeOption */
    TaskTypeOption: {
      /** Value */
      value: string;
      /** Label */
      label: string;
    };
    /** TaskTypeRead */
    TaskTypeRead: {
      /** Type */
      type: string;
      /** Label */
      label: string;
      /** Options */
      options: components["schemas"]["TaskTypeOption"][];
      /** Accepts Time */
      accepts_time: boolean;
      /** Has Other */
      has_other: boolean;
      /** Other Min */
      other_min?: number | null;
    };
    /**
     * TaskUpdate
     * @description PATCH /v1/tasks/{task_id}. `type` is accepted only to answer 422 FIELD_NOT_EDITABLE (ACT-R3).
     */
    TaskUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Status */
      status?: ("ACTIVE" | "INACTIVE") | null;
      /** Type */
      type?: string | null;
    };
    /**
     * TodoAnswer
     * @description PATCH /v1/me/todos/{todo_id} — the answer is validated against the task type (ASG-R22).
     */
    TodoAnswer: {
      /** Response Value */
      response_value: string;
      /**
       * Is Other
       * @default false
       */
      is_other: boolean;
    };
    /** TodoRead */
    TodoRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Assignment Id
       * Format: uuid
       */
      assignment_id: string;
      task: components["schemas"]["TodoTaskRead"];
      /**
       * Due Date
       * Format: date
       */
      due_date: string;
      /** Frequency */
      frequency: string;
      /** Status */
      status: string;
      /** Response Value */
      response_value: string | null;
      /** Is Other */
      is_other: boolean;
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TodoTaskRead */
    TodoTaskRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Type */
      type: string;
    };
    /** TokenPairRead */
    TokenPairRead: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /** Token Type */
      token_type: string;
      /** Expires In */
      expires_in: number;
      user: components["schemas"]["LoginUserRead"];
    };
    /** UserDeletePreviewRead */
    UserDeletePreviewRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Status */
      status: string;
      /** Assignments */
      assignments: number;
      /** Todos Total */
      todos_total: number;
      /** Todos Completed */
      todos_completed: number;
    };
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      role: components["schemas"]["RoleRead"];
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Created By */
      created_by: string | null;
      /** Updated By */
      updated_by: string | null;
    };
    /**
     * UserStatusUpdate
     * @description PATCH /v1/users/{user_id} — activate or deactivate.
     */
    UserStatusUpdate: {
      /**
       * Status
       * @enum {string}
       */
      status: "ACTIVE" | "INACTIVE";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** YearPending */
    YearPending: {
      /** Year */
      year: number;
      /** Pending */
      pending: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_me_v1_me_get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_UserRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_me_v1_me_patch: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_UserRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_roles_v1_roles_get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_RoleListRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_users_v1_users_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
        status?: ("INVITED" | "ACTIVE" | "INACTIVE") | null;
        role?: ("ADMIN" | "USER") | null;
        sort_by?: "first_name" | "email" | "created_at";
        sort_order?: "asc" | "desc";
      };
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PaginatedResponse_UserRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_v1_users__user_id__get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_UserRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_user_v1_users__user_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  change_user_status_v1_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_UserRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TokenPairRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  token_v1_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_token_v1_auth_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OAuth2TokenRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TokenPairRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_permissions_v1_me_permissions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_MyPermissionsRead_"];
        };
      };
    };
  };
  change_password_v1_me_password_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_NoneType_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  invite_v1_invitations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_InviteResultRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_invitation_v1_invitations_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkTokenRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_InvitationInfoRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  accept_invitation_v1_invitations_accept_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInvitationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_AcceptInvitationRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resend_invitation_v1_users__user_id__invitations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_ResendInvitationRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  forgot_password_v1_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_NoneType_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_password_link_v1_users__user_id__password_links_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PasswordLinkRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_reset_v1_auth_reset_password_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkTokenRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_ResetInfoRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_password_v1_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_NoneType_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_task_types_v1_task_types_get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TaskTypeListRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_v1_tasks_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
        type?: ("TIME" | "YES_NO" | "FOOD" | "NUMBER") | null;
        status?: ("ACTIVE" | "INACTIVE") | null;
        sort_by?: "name" | "updated_at";
        sort_order?: "asc" | "desc";
      };
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PaginatedResponse_TaskRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_task_v1_tasks_post: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TaskRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_v1_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TaskRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_task_v1_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_task_v1_tasks__task_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TaskRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_assignments_v1_assignments_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        user_id?: string | null;
        task_id?: string | null;
        frequency?:
          | (
              | "DAILY"
              | "WEEKLY"
              | "EVERY_15_DAYS"
              | "MONTHLY"
              | "QUARTERLY"
              | "SIX_MONTHS"
              | "YEARLY"
            )
          | null;
        status?: "ACTIVE" | "ENDED" | "ALL";
        sort_by?: "user_name" | "task_name" | "start_date" | "created_at";
        sort_order?: "asc" | "desc";
      };
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PaginatedResponse_AssignmentRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assign_task_v1_assignments_post: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_AssignResultRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  copy_assignments_v1_assignments_copy_post: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CopyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_CopyResultRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  due_dates_preview_v1_assignments_due_dates_preview_get: {
    parameters: {
      query: {
        frequency:
          "DAILY" | "WEEKLY" | "EVERY_15_DAYS" | "MONTHLY" | "QUARTERLY" | "SIX_MONTHS" | "YEARLY";
        weekdays?: string | null;
        start_date?: string | null;
        end_date?: string | null;
        count?: number;
      };
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_DueDatesRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_assignment_v1_assignments__assignment_id__get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        assignment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_AssignmentRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_assignment_v1_assignments__assignment_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
        "If-None-Match"?: string | null;
      };
      path: {
        assignment_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_AssignmentRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_todos_v1_me_todos_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        date?: string | null;
        frequency?:
          | (
              | "DAILY"
              | "WEEKLY"
              | "EVERY_15_DAYS"
              | "MONTHLY"
              | "QUARTERLY"
              | "SIX_MONTHS"
              | "YEARLY"
            )
          | null;
        search?: string | null;
      };
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PaginatedResponse_TodoRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_calendar_v1_me_todos_calendar_get: {
    parameters: {
      query?: {
        month?: string | null;
      };
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_CalendarRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_pending_counts_v1_me_todos_pending_counts_get: {
    parameters: {
      query?: {
        year?: number | null;
      };
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PendingCountsRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_summary_v1_me_todos_summary_get: {
    parameters: {
      query?: {
        date?: string | null;
      };
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_SummaryRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  answer_todo_v1_me_todos__todo_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
      };
      path: {
        todo_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TodoAnswer"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TodoRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_history_v1_me_history_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        date_from?: string | null;
        date_to?: string | null;
        task_id?: string | null;
        frequency?:
          | (
              | "DAILY"
              | "WEEKLY"
              | "EVERY_15_DAYS"
              | "MONTHLY"
              | "QUARTERLY"
              | "SIX_MONTHS"
              | "YEARLY"
            )
          | null;
      };
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PaginatedResponse_HistoryItemRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_tasks_v1_me_tasks_get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_MyTaskListRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  all_history_v1_history_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        date_from?: string | null;
        date_to?: string | null;
        task_id?: string | null;
        frequency?:
          | (
              | "DAILY"
              | "WEEKLY"
              | "EVERY_15_DAYS"
              | "MONTHLY"
              | "QUARTERLY"
              | "SIX_MONTHS"
              | "YEARLY"
            )
          | null;
        user_id?: string | null;
      };
      header?: {
        "If-Match"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_PaginatedResponse_HistoryItemRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  user_delete_preview_v1_users__user_id__delete_preview_get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_UserDeletePreviewRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  task_delete_preview_v1_tasks__task_id__delete_preview_get: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_TaskDeletePreviewRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_report_v1_reports_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        range_type?: "DAY" | "WEEK" | "MONTH" | "CUSTOM";
        day?: string | null;
        week_start?: string | null;
        month?: string | null;
        date_from?: string | null;
        date_to?: string | null;
        user_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_ReportRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_my_report_v1_me_report_get: {
    parameters: {
      query?: {
        range_type?: "DAY" | "WEEK" | "MONTH" | "CUSTOM";
        day?: string | null;
        week_start?: string | null;
        month?: string | null;
        date_from?: string | null;
        date_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandardResponse_MyReportRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
